[project]
name = "sla-api"
version = "0.1.0"
dependencies = [
  "fastapi[standard]",
  "pydantic-settings",
  "openai>=1.40.0",
  "anthropic>=0.34.0",
  "requests>=2.32.0",
  "sqlalchemy",
  "psycopg[binary]",
  "pgvector",
  "uvicorn[standard]"
]
